# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
      - "application"
    assignees:
      - "theendofline"
    groups:
      production-dependencies-major:
        dependency-type: production
        update-types:
          - "major"
      production-dependencies-minor:
        dependency-type: production
        update-types:
          - "minor"
      production-dependencies-patch:
        dependency-type: production
        update-types:
          - "patch"
      development-dependencies-major:
        dependency-type: development
        update-types:
          - "major"
      development-dependencies-minor:
        dependency-type: development
        update-types:
          - "minor"
      development-dependencies-patch:
        dependency-type: development
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    assignees:
      - "theendofline"
