# Ruff configuration file

target-version = "py312"
line-length = 100

# Per-file ignores
[lint.per-file-ignores]
"__init__.py" = ["N999"]
"tests/__init__.py" = ["N999"]

[lint]
select = ["E", "F", "I", "W", "N", "B", "C4", "ARG", "SIM"]
ignore = []
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
]

[lint.isort]
known-first-party = ["widget"]
known-third-party = ["PySide6", "PIL"]

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single" 