# Ruff configuration file

target-version = "py312"
line-length = 100
select = ["E", "F", "I", "W", "N", "B", "C4", "ARG", "SIM"]
ignore = []
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
]

[isort]
known-first-party = ["widget"]
known-third-party = ["PySide6", "PIL"]

[flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single" 