name: Build and Release AppImage

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 desktop-file-utils libglib2.0-bin

      - name: Set up environment
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          pip install -e .

      - name: Build AppImage
        run: |
          source .venv/bin/activate
          python scripts/build_appimage.py

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: dist/*.AppImage

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
